spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pkq03?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: providerBoot
eureka:
    client:
      service-url:
        defaultZone: http://zjjnb1109000.com:9000/eureka/, http://zjjnb1109001.com:9001/eureka/, http://zjjnb1109002.com:9002/eureka/
    instance:
      instance-id: provider-boot-User8090 #自定义服务名称
      prefer-ip-address: true       #访问路径显示ip地址
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: pkq.com.bean
server:
  port: 8090
info:
  app.name: pkq-provider-boot
  company.ñame: www.pkq.com
  build.artifactld: $project.artifactId$
  build.version: $project.version$