eureka:
  client:
    service-url:
      defaultZone: http://zjjnb1109000.com:9000/eureka/, http://zjjnb1109001.com:9001/eureka/, http://zjjnb1109002.com:9002/eureka/
  instance:
    instance-id: provider-boot-User8000 #自定义服务名称
    prefer-ip-address: true       #访问路径显示ip地址
server:
  port: 3456
spring:
  application:
    name: consumer-demo-boot