spring:
  application:
    name: spring-cloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://zjjnb1109000.com:9000/eureka/, http://zjjnb1109001.com:9001/eureka/, http://zjjnb1109002.com:9002/eureka/
  instance:
    instance-id: spring-cloud-zuul:1000 #自定义服务名称
    prefer-ip-address: true       #访问路径显示ip地址
server:
  port: 1236
info:
  app.name: spring-cloud-zuul:1000
  company.ñame: www.pkq.com
  build.artifactld: $project.artifactId$
  build.version: $project.version$


zuul:
  routes:
    ###定义转发服务规则（随便起名）
    meiszl-member:
      ###以/api-member/访问转发到会员服务
      path: /api-member/**
      ###服务别名 zuul网关默认整合ribbon 自动实现负载均衡轮训效果
      serviceId: PROVIDERBOOT
    meiszl-order:
      ###以/api-order/访问转发到订单服务
      path: /api-order/**
      ###订单服务别名
      serviceId: PROVIDERBOOT
